name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    name: Use this action for check
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    permissions:
      contents: read # for checkout
      pull-requests: write # for this action
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Use this action
        uses: ./
        with:
          comment: 'CI ( ${{ matrix.runner }} ) passed. ref: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          previous-comment: 'hide'
          grouping-key: ${{ matrix.runner }}-${{ github.workflow }}-${{ github.job }}
